# ============================================================
# Project:  Hobby Tracker API
# File:     main.py
# Author:   Harshitha Sathees Kumar
# Date:     2026-03-25
# Description:
#   REST API built with FastAPI for tracking hobby sessions.
#   Supports baking, crochet, and pottery entries.
#   Uses SQLite for permanent storage (data survives restarts).
#
# Run:
#   uvicorn main:app --reload
#
# Docs (auto-generated by FastAPI):
#   http://127.0.0.1:8000/docs
#
# Endpoints:
#   POST   /hobbies                    Create a new hobby entry
#   GET    /hobbies                    Get all entries (filter: ?hobby_type=)
#   GET    /hobbies/{id}               Get one entry by id
#   PUT    /hobbies/{id}               Update an entry by id
#   DELETE /hobbies/{id}               Delete an entry by id
# ============================================================


# ============================================================
# IMPORTS
# ============================================================

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional, List
from datetime import date
import sqlite3


# ============================================================
# APP INITIALIZATION
# ============================================================

app = FastAPI(
    title="Hobby Tracker API",
    description="Backend API for tracking baking, crochet, and pottery sessions.",
    version="1.0.0",
)


# ============================================================
# CORS MIDDLEWARE
# ============================================================
# Allows the frontend to communicate with this backend.

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# FRIENDLY ERROR HANDLERS
# ============================================================

@app.exception_handler(RequestValidationError)
async def validation_error_handler(request, exc):
    return JSONResponse(
        status_code=400,
        content={"message": "Hmm, something doesn't look right! Make sure all fields are filled in correctly and give it another try 😊"}
    )

@app.exception_handler(404)
async def not_found_handler(request, exc):
    return JSONResponse(
        status_code=404,
        content={"message": "We looked everywhere but couldn't find that entry! It may have already been deleted 🔍"}
    )

@app.exception_handler(500)
async def server_error_handler(request, exc):
    return JSONResponse(
        status_code=500,
        content={"message": "Oops, something went wrong on our end! Give it a moment and try again 🙈"}
    )


# ============================================================
# CONSTANTS
# ============================================================

VALID_HOBBY_TYPES = {"baking", "crochet", "pottery"}


# ============================================================
# DATABASE SETUP
# ============================================================
# SQLite stores everything in a single file called hobbies.db
# This file sits in your project folder and survives restarts.
# get_db() opens a connection to the file whenever we need it.
# init_db() creates the hobbies table if it doesn't exist yet.

DB_NAME = "hobbies.db"

def get_db():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row  # lets us access columns by name instead of index
    return conn

def init_db():
    conn = get_db()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS hobbies (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            hobby_type  TEXT    NOT NULL,
            title       TEXT    NOT NULL,
            date        TEXT    NOT NULL,
            completed   INTEGER NOT NULL,
            duration    INTEGER NOT NULL,
            notes       TEXT
        )
    """)
    conn.commit()
    conn.close()

# Run init_db when the server starts so the table is always ready
init_db()


# ============================================================
# DATA MODELS (Pydantic)
# ============================================================
# HobbyEntry       — used for POST (creating a new entry)
# HobbyEntryUpdate — used for PUT (updating an existing entry)
#                    All fields are Optional so the frontend
#                    only needs to send what changed.

class HobbyEntry(BaseModel):
    hobby_type: str                  # Must be: "baking", "crochet", or "pottery"
    title: str                       # What the user worked on
    date: date                       # Format: YYYY-MM-DD (validated automatically)
    completed: bool                  # True = completed, False = not completed
    duration: int                    # Time spent in minutes
    notes: Optional[str] = None      # Short reflection (optional)


class HobbyEntryUpdate(BaseModel):
    hobby_type: Optional[str] = None
    title: Optional[str] = None
    date: Optional[date] = None
    completed: Optional[bool] = None
    duration: Optional[int] = None
    notes: Optional[str] = None


# ============================================================
# HELPER FUNCTION
# ============================================================
# Converts a database row into a clean Python dictionary
# so FastAPI can turn it into JSON easily.

def row_to_dict(row):
    return {
        "id":         row["id"],
        "hobby_type": row["hobby_type"],
        "title":      row["title"],
        "date":       row["date"],
        "completed":  bool(row["completed"]),  # SQLite stores 0/1, we want True/False
        "duration":   row["duration"],
        "notes":      row["notes"],
    }


# ============================================================
# ROUTES
# ============================================================


# --- Health Check ---
@app.get("/", tags=["Health"])
def root():
    """
    Health check endpoint.
    Returns a message confirming the API is running.
    """
    return {"message": "Hey there! The Hobby Tracker API is up and running 🎨"}


# --- Create a new hobby entry ---
@app.post("/hobbies", status_code=201, tags=["Hobbies"])
def create_hobby(entry: HobbyEntry):
    """
    Creates a new hobby entry and saves it to the database.

    - Validates that hobby_type is one of: baking, crochet, pottery
    - Auto-generates a unique id
    - Returns the created entry including the new id
    """
    if entry.hobby_type not in VALID_HOBBY_TYPES:
        raise HTTPException(
            status_code=400,
            detail="That hobby type doesn't exist! Stick to baking, crochet, or pottery 🎨"
        )

    conn = get_db()
    cursor = conn.execute(
        "INSERT INTO hobbies (hobby_type, title, date, completed, duration, notes) VALUES (?, ?, ?, ?, ?, ?)",
        (entry.hobby_type, entry.title, str(entry.date), int(entry.completed), entry.duration, entry.notes)
    )
    conn.commit()

    # Fetch the newly created entry so we can return it with its auto-generated id
    new_entry = conn.execute("SELECT * FROM hobbies WHERE id = ?", (cursor.lastrowid,)).fetchone()
    conn.close()

    return row_to_dict(new_entry)


# --- Get all hobby entries (with optional filter) ---
@app.get("/hobbies", tags=["Hobbies"])
def get_hobbies(hobby_type: Optional[str] = None):
    """
    Returns all hobby entries from the database.

    - Optional query parameter: ?hobby_type=baking
    - Filters results by hobby type when provided
    - Returns all entries when no filter is given
    """
    conn = get_db()

    if hobby_type:
        rows = conn.execute(
            "SELECT * FROM hobbies WHERE hobby_type = ?", (hobby_type,)
        ).fetchall()
    else:
        rows = conn.execute("SELECT * FROM hobbies").fetchall()

    conn.close()
    return [row_to_dict(row) for row in rows]


# --- Get a single hobby entry by id ---
@app.get("/hobbies/{hobby_id}", tags=["Hobbies"])
def get_hobby(hobby_id: int):
    """
    Returns a single hobby entry by its id.

    - Returns a friendly 404 message if the id does not exist
    """
    conn = get_db()
    row = conn.execute("SELECT * FROM hobbies WHERE id = ?", (hobby_id,)).fetchone()
    conn.close()

    if not row:
        raise HTTPException(
            status_code=404,
            detail="We couldn't find that hobby entry! Double check the ID and try again 🔍"
        )

    return row_to_dict(row)


# --- Update an existing hobby entry ---
@app.put("/hobbies/{hobby_id}", tags=["Hobbies"])
def update_hobby(hobby_id: int, updates: HobbyEntryUpdate):
    """
    Updates an existing hobby entry by its id.

    - Only updates fields that are provided in the request body
    - Fields not included in the request remain unchanged
    - Returns the updated entry
    - Returns a friendly 404 message if the id does not exist
    """
    conn = get_db()

    # First check the entry actually exists
    existing = conn.execute("SELECT * FROM hobbies WHERE id = ?", (hobby_id,)).fetchone()
    if not existing:
        conn.close()
        raise HTTPException(
            status_code=404,
            detail="We couldn't find that hobby entry! Double check the ID and try again 🔍"
        )

    # Validate hobby_type if it's being updated
    if updates.hobby_type is not None and updates.hobby_type not in VALID_HOBBY_TYPES:
        conn.close()
        raise HTTPException(
            status_code=400,
            detail="That hobby type doesn't exist! Stick to baking, crochet, or pottery 🎨"
        )

    # Build the update dynamically — only update fields that were actually sent
    fields = []
    values = []

    if updates.hobby_type is not None:
        fields.append("hobby_type = ?")
        values.append(updates.hobby_type)
    if updates.title is not None:
        fields.append("title = ?")
        values.append(updates.title)
    if updates.date is not None:
        fields.append("date = ?")
        values.append(str(updates.date))
    if updates.completed is not None:
        fields.append("completed = ?")
        values.append(int(updates.completed))
    if updates.duration is not None:
        fields.append("duration = ?")
        values.append(updates.duration)
    if updates.notes is not None:
        fields.append("notes = ?")
        values.append(updates.notes)

    if fields:
        values.append(hobby_id)
        conn.execute(f"UPDATE hobbies SET {', '.join(fields)} WHERE id = ?", values)
        conn.commit()

    updated = conn.execute("SELECT * FROM hobbies WHERE id = ?", (hobby_id,)).fetchone()
    conn.close()

    return row_to_dict(updated)


# --- Delete a hobby entry ---
@app.delete("/hobbies/{hobby_id}", tags=["Hobbies"])
def delete_hobby(hobby_id: int):
    """
    Deletes a hobby entry by its id.

    - Returns a friendly confirmation message on success
    - Returns a friendly 404 message if the id does not exist
    """
    conn = get_db()

    # Check entry exists before trying to delete
    existing = conn.execute("SELECT * FROM hobbies WHERE id = ?", (hobby_id,)).fetchone()
    if not existing:
        conn.close()
        raise HTTPException(
            status_code=404,
            detail="We couldn't find that hobby entry! Double check the ID and try again 🔍"
        )

    conn.execute("DELETE FROM hobbies WHERE id = ?", (hobby_id,))
    conn.commit()
    conn.close()

    return {"message": f"Entry #{hobby_id} has been deleted successfully! Hope you had fun 🌟"}