# ============================================================
# Project:  Hobby Tracker API
# File:     main.py
# Author:   Harshitha Sathees Kumar
# Date:     2026-03-25
# Description:
#   REST API built with FastAPI for tracking hobby sessions.
#   Supports baking, crochet, and pottery entries.
#   Uses in-memory storage (no database just lists).
#
# Run:
#   uvicorn main:app --reload
#
# Docs (auto-generated by FastAPI):
#   http://127.0.0.1:8000/docs
#
# Endpoints:
#   POST   /hobbies                    Create a new hobby entry
#   GET    /hobbies                    Get all entries (filter: ?hobby_type=)
#   GET    /hobbies/{id}               Get one entry by id
#   PUT    /hobbies/{id}               Update an entry by id
#   DELETE /hobbies/{id}               Delete an entry by id
# ============================================================


# ============================================================
# IMPORTS
# ============================================================

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional, List
from datetime import date


# ============================================================
# APP INITIALIZATION
# ============================================================

app = FastAPI(
    title="Hobby Tracker API",
    description="Backend API for tracking baking, crochet, and pottery sessions.",
    version="1.0.0",
)


# ============================================================
# CORS MIDDLEWARE
# ============================================================
# Allows the frontend to communicate with this backend.


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# ERROR HANDLERS
# ============================================================
# These catch errors and return messages

@app.exception_handler(RequestValidationError)
async def validation_error_handler(request, exc):
    return JSONResponse(
        status_code=400,
        content={"message": "Hmm, something doesn't look right! Make sure all fields are filled in correctly and give it another try 😊"}
    )

@app.exception_handler(404)
async def not_found_handler(request, exc):
    return JSONResponse(
        status_code=404,
        content={"message": "We looked everywhere but couldn't find that entry! It may have already been deleted 🔍"}
    )

@app.exception_handler(500)
async def server_error_handler(request, exc):
    return JSONResponse(
        status_code=500,
        content={"message": "Oops, something went wrong on our end! Give it a moment and try again 🙈"}
    )


# ============================================================
# CONSTANTS
# ============================================================

VALID_HOBBY_TYPES = {"baking", "crochet", "pottery"}


# ============================================================
# DATA MODELS (Pydantic)
# ============================================================
# HobbyEntry       — used for POST (creating a new entry)
# HobbyEntryUpdate — used for PUT (updating an existing entry)
#                    All fields are Optional so the frontend
#                    only needs to send what changed.

class HobbyEntry(BaseModel):
    hobby_type: str                  # Must be: "baking", "crochet", or "pottery"
    title: str                       # What the user worked on
    date: date                       # Format: YYYY-MM-DD (validated automatically)
    completed: bool                  # True = completed, False = not completed
    duration: int                    # Time spent in minutes
    notes: Optional[str] = None      # Short reflection (optional)


class HobbyEntryUpdate(BaseModel):
    hobby_type: Optional[str] = None
    title: Optional[str] = None
    date: Optional[date] = None
    completed: Optional[bool] = None
    duration: Optional[int] = None
    notes: Optional[str] = None


# ============================================================
# IN-MEMORY STORAGE
# ============================================================
# Acts as the database for this project.
# hobby_list stores all entries as dictionaries.
# id_counter auto-increments to give each entry a unique id.
# Note: all data resets when the server restarts.

hobby_list: List[dict] = []
id_counter: int = 1


# ============================================================
# ROUTES
# ============================================================


# --- Health Check ---
@app.get("/", tags=["Health"])
def root():
    """
    Health check endpoint.
    Returns a message confirming the API is running.
    """
    return {"message": "Hey there! The Hobby Tracker API is up and running 🎨"}


# --- Create a new hobby entry ---
@app.post("/hobbies", status_code=201, tags=["Hobbies"])
def create_hobby(entry: HobbyEntry):
    """
    Creates a new hobby entry.

    - Validates that hobby_type is one of: baking, crochet, pottery
    - Auto-generates a unique id
    - Returns the created entry including the new id
    """
    global id_counter

    if entry.hobby_type not in VALID_HOBBY_TYPES:
        raise HTTPException(
            status_code=400,
            detail="That hobby type doesn't exist! Stick to baking, crochet, or pottery 🎨"
        )

    new_entry = {
        "id": id_counter,
        "hobby_type": entry.hobby_type,
        "title": entry.title,
        "date": str(entry.date),
        "completed": entry.completed,
        "duration": entry.duration,
        "notes": entry.notes,
    }

    hobby_list.append(new_entry)
    id_counter += 1

    return new_entry


# --- Get all hobby entries (with optional filter) ---
@app.get("/hobbies", tags=["Hobbies"])
def get_hobbies(hobby_type: Optional[str] = None):
    """
    Returns all hobby entries.

    - Optional query parameter: ?hobby_type=baking
    - Filters results by hobby type when provided
    - Returns all entries when no filter is given
    """
    if hobby_type:
        filtered = [h for h in hobby_list if h["hobby_type"] == hobby_type]
        return filtered
    return hobby_list


# --- Get a single hobby entry by id ---
@app.get("/hobbies/{hobby_id}", tags=["Hobbies"])
def get_hobby(hobby_id: int):
    """
    Returns a single hobby entry by its id.

    - Returns a friendly 404 message if the id does not exist
    """
    for hobby in hobby_list:
        if hobby["id"] == hobby_id:
            return hobby

    raise HTTPException(
        status_code=404,
        detail="We couldn't find that hobby entry! Double check the ID and try again 🔍"
    )


# --- Update an existing hobby entry ---
@app.put("/hobbies/{hobby_id}", tags=["Hobbies"])
def update_hobby(hobby_id: int, updates: HobbyEntryUpdate):
    """
    Updates an existing hobby entry by its id.

    - Only updates fields that are provided in the request body
    - Fields not included in the request remain unchanged
    - Returns the updated entry
    - Returns a friendly 404 message if the id does not exist
    """
    for hobby in hobby_list:
        if hobby["id"] == hobby_id:

            if updates.hobby_type is not None:
                if updates.hobby_type not in VALID_HOBBY_TYPES:
                    raise HTTPException(
                        status_code=400,
                        detail="That hobby type doesn't exist! Stick to baking, crochet, or pottery 🎨"
                    )
                hobby["hobby_type"] = updates.hobby_type

            if updates.title is not None:
                hobby["title"] = updates.title
            if updates.date is not None:
                hobby["date"] = str(updates.date)
            if updates.completed is not None:
                hobby["completed"] = updates.completed
            if updates.duration is not None:
                hobby["duration"] = updates.duration
            if updates.notes is not None:
                hobby["notes"] = updates.notes

            return hobby

    raise HTTPException(
        status_code=404,
        detail="We couldn't find that hobby entry! Double check the ID and try again 🔍"
    )


# --- Delete a hobby entry ---
@app.delete("/hobbies/{hobby_id}", tags=["Hobbies"])
def delete_hobby(hobby_id: int):
    """
    Deletes a hobby entry by its id.

    - Returns a friendly confirmation message on success
    - Returns a friendly 404 message if the id does not exist
    """
    for index, hobby in enumerate(hobby_list):
        if hobby["id"] == hobby_id:
            hobby_list.pop(index)
            return {"message": f"Entry #{hobby_id} has been deleted successfully! Hope you had fun 🌟"}

    raise HTTPException(
        status_code=404,
        detail="We couldn't find that hobby entry! Double check the ID and try again 🔍"
    )

